Formatting: Braces around variables

diff --git a/muxsh b/muxsh
--- a/muxsh
+++ b/muxsh
@@ -25,10 +25,10 @@ VERSION="0.1.5"
 
 # Variables
 dependencies=(fzf java mkvmerge curl sed grep cut)
-folder="${XDG_CACHE_HOME:-$HOME/.cache}/subkt"
-output="$folder/subkt.txt"
-config_folder="${XDG_CONFIG_HOME:-$HOME/.config}/muxkt"
-config="$config_folder/config"
+folder="${XDG_CACHE_HOME:-${HOME}/.cache}/subkt"
+output="${folder}/subkt.txt"
+config_folder="${XDG_CONFIG_HOME:-${HOME}/.config}/muxkt"
+config="${config_folder}/config"
 
 # Animations
 # https://github.com/Silejonu/bash_loading_animations
@@ -37,7 +37,7 @@ active_loading_animation=("${passing_dots[@]}")
 # Extract the delay between each frame from the active_loading_animation array
 loading_animation_speed="${active_loading_animation[0]}"
 unset "active_loading_animation[0]"
-# Stop the animation and restore the normal cursor if the script is interrupted
+# Stop the animation and restore the normal  if the script is interrupted
 trap stop_loading_animation SIGINT
 
 loading_animation() {
@@ -62,9 +62,9 @@ stop_loading_animation() {
 }
 
 # Create required directories and config file if they're not present
-[[ ! -d "$folder" ]] && mkdir -p "$folder"
-[[ ! -d "$config_folder" ]] && mkdir -p "$config_folder"
-[[ -f "$config" ]] || : >"$config"
+[[ ! -d "${folder}" ]] && mkdir -p "${folder}"
+[[ ! -d "${config_folder}" ]] && mkdir -p "${config_folder}"
+[[ -f "${config}" ]] || : >"${config}"
 
 # Functions
 die() {
@@ -83,7 +83,7 @@ green_text() {
 # Check for update
 check_update() {
 	update="$(curl -s "https://raw.githubusercontent.com/PhosCity/muxsh/main/muxsh" | diff -u "$0" -)"
-	if [[ -n "$update" ]]; then
+	if [[ -n "${update}" ]]; then
 		printf "There seems to be a new version available in github.\nPlease get it from https://github.com/PhosCity/muxsh \n"
 		sleep 3
 	fi
@@ -92,7 +92,7 @@ check_update() {
 # Check dependencies
 dep_ch() {
 	for dep; do
-		if ! command -v "$dep" >/dev/null; then
+		if ! command -v "${dep}" >/dev/null; then
 			missing_dep="${missing_dep}\"${dep}\" "
 		fi
 	done
@@ -100,35 +100,35 @@ dep_ch() {
 
 # Read config and get all the key, value pair for a particular section
 get_section() {
-	section_data=$(sed "0,/^\[$1\]$/d" "$config" | sed '/^$/Q;/\[.*\]/d')
-	echo "$section_data"
+	section_data=$(sed "0,/^\[$1\]$/d" "${config}" | sed '/^$/Q;/\[.*\]/d')
+	echo "${section_data}"
 }
 
 # Add project to the config
 config_add() {
-	if ! grep -q "\[Project\]" "$config"; then
+	if ! grep -q "\[Project\]" "${config}"; then
 		echo "Config does not exist. Creating new one."
-		printf "[Project]\n\n" >>"$config"
+		printf "[Project]\n\n" >>"${config}"
 	fi
 	while :; do
 		printf "Name of Project: "
 		read -r prj
-		if [[ -z "$prj" ]]; then
+		if [[ -z "${prj}" ]]; then
 			echo "Project is needed for continuing."
 		else
 			printf "Path of the project: "
 			read -r pth
-			if [[ ! -d "$pth" ]]; then
+			if [[ ! -d "${pth}" ]]; then
 				echo "Not a valid path."
 				pth=""
 			fi
 		fi
-		if [[ -n "$prj" ]] && [[ -n "$pth" ]]; then
-			sed -i "/\[Project\]/a $prj = $pth" "$config"
+		if [[ -n "${prj}" ]] && [[ -n "${pth}" ]]; then
+			sed -i "/\[Project\]/a ${prj} = ${pth}" "${config}"
 		fi
 		printf "Do you want to continue adding projects[y/n]: "
 		read -r cont
-		case "$cont" in
+		case "${cont}" in
 			y) ;;
 			*) break ;;
 		esac
@@ -138,14 +138,14 @@ config_add() {
 # Remove project from the config
 # TODO: Not a good implementation rn. Fix
 config_remove() {
-	if ! grep -q "\[Project\]" "$config"; then
+	if ! grep -q "\[Project\]" "${config}"; then
 		echo "There are no projects in the config to remove."
 	else
 		project=$(get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g" | fzf)
-		to_delete=$(get_section "Project" | grep "$project")
-		line_to_delete=$(grep -n -F -x "$to_delete" "$config" | cut -d: -f1)
-		sed -i "${line_to_delete}d" "$config"
-		echo "Removed $project from the config"
+		to_delete=$(get_section "Project" | grep "${project}")
+		line_to_delete=$(grep -n -F -x "${to_delete}" "${config}" | cut -d: -f1)
+		sed -i "${line_to_delete}d" "${config}"
+		echo "Removed ${project} from the config"
 	fi
 }
 
@@ -153,15 +153,15 @@ config_remove() {
 # Then cd to that directory.
 # Also if config is not found, then prompt user to add one.
 change_directory() {
-	if [[ -z "$project" ]]; then
-		if ! grep -q "\[Project\]" "$config"; then
+	if [[ -z "${project}" ]]; then
+		if ! grep -q "\[Project\]" "${config}"; then
 			config_add
 		fi
 		project=$(get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g" | fzf)
 	fi
-	[[ -z "$project" ]] && die "Project was not selected by the user."
-	[[ -z "$project_path" ]] && project_path=$(get_section "Project" | grep "$project" | cut -d= -f2 | sed "s/\"//g;s/^ //g")
-	cd "$project_path" || die "Path in config is not correct."
+	[[ -z "${project}" ]] && die "Project was not selected by the user."
+	[[ -z "${project_path}" ]] && project_path=$(get_section "Project" | grep "${project}" | cut -d= -f2 | sed "s/\"//g;s/^ //g")
+	cd "${project_path}" || die "Path in config is not correct."
 }
 
 check_episode() {
@@ -175,7 +175,7 @@ check_episode() {
 
 help_text() {
 	while IFS= read -r line; do
-		printf "%s\n" "$line"
+		printf "%s\n" "${line}"
 	done <<EOF
 USAGE: ${0##*/} [OPTIONS] arguments
 [OPTIONS]
@@ -192,10 +192,10 @@ EOF
 }
 
 while getopts ':p:hon:e:rac:v' OPT; do
-	case $OPT in
+	case ${OPT} in
 		:)
-			red_text "Please provide an argument to -$OPTARG"
-			help_text | grep -e "USAGE" -e "-$OPTARG"
+			red_text "Please provide an argument to -${OPTARG}"
+			help_text | grep -e "USAGE" -e "-${OPTARG}"
 			exit 2
 			;;
 		h)
@@ -203,31 +203,31 @@ while getopts ':p:hon:e:rac:v' OPT; do
 			exit 0
 			;;
 		o)
-			cat "$output"
+			cat "${output}"
 			exit 0
 			;;
 		p)
-			if [[ ! -d "$OPTARG" ]]; then
-				die "$OPTARG is not a valid path."
+			if [[ ! -d "${OPTARG}" ]]; then
+				die "${OPTARG} is not a valid path."
 			else
-				project_path="$OPTARG"
-				project="$OPTARG"
-				cd "$project_path" || exit 1
+				project_path="${OPTARG}"
+				project="${OPTARG}"
+				cd "${project_path}" || exit 1
 			fi
 			;;
 		n)
-			[[ -s "$config" ]] || die "No content found in config. Please add your projects to the config which is located at $config_folder"
+			[[ -s "${config}" ]] || die "No content found in config. Please add your projects to the config which is located at ${config_folder}"
 
-			project=$(get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g" | grep -x "$OPTARG")
-			if [[ -z "$project" ]]; then
-				printf "The project named %s could not be found in the config.\n" "$OPTARG"
+			project=$(get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g" | grep -x "${OPTARG}")
+			if [[ -z "${project}" ]]; then
+				printf "The project named %s could not be found in the config.\n" "${OPTARG}"
 				printf "The available projects are:\n"
 				get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g"
 				exit 2
 			fi
 			;;
 		e)
-			check_episode "$OPTARG"
+			check_episode "${OPTARG}"
 			;;
 		r)
 			project="Repeat Last"
@@ -236,18 +236,18 @@ while getopts ':p:hon:e:rac:v' OPT; do
 			alt_folder="yes"
 			;;
 		c)
-			case "$OPTARG" in
+			case "${OPTARG}" in
 				"add") config_add ;;
 				"remove") config_remove ;;
 				*)
 					echo "Not a valid argument."
-					help_text | grep -e "USAGE" -e "-$OPT"
+					help_text | grep -e "USAGE" -e "-${OPT}"
 					;;
 			esac
 			exit 0
 			;;
 		v)
-			echo "muxsh, Version: $VERSION"
+			echo "muxsh, Version: ${VERSION}"
 			exit 0
 			;;
 		*)
@@ -358,89 +358,89 @@ check_update
 
 # check for main dependencies
 for i in "${dependencies[@]}"; do
-	dep_ch "$i"
+	dep_ch "${i}"
 done
-[[ -n "$missing_dep" ]] && die "${missing_dep}not found. Please install all missing dependencies."
+[[ -n "${missing_dep}" ]] && die "${missing_dep}not found. Please install all missing dependencies."
 
 # Read History
-if [[ "$project" = "Repeat Last" ]]; then
+if [[ "${project}" = "Repeat Last" ]]; then
 	_hist=$(get_section "History" | tr -d "\n")
-	project=$(cut -d= -f1 <<<"$_hist" | sed "s/[[:space:]]*$//")
-	project_path=$(cut -d= -f2 <<<"$_hist" | cut -d';' -f1 | sed "s/^ //")
-	episode=$(cut -d= -f2 <<<"$_hist" | cut -d';' -f2 | tr -d "\n" | tr "," "\n")
+	project=$(cut -d= -f1 <<<"${_hist}" | sed "s/[[:space:]]*$//")
+	project_path=$(cut -d= -f2 <<<"${_hist}" | cut -d';' -f1 | sed "s/^ //")
+	episode=$(cut -d= -f2 <<<"${_hist}" | cut -d';' -f2 | tr -d "\n" | tr "," "\n")
 fi
 
 # Read query (Should be given in `<path to script> <project> <episode>` format)
 if [[ -n "$*" ]]; then
 	query="$*"
 	# shellcheck disable=SC2001
-	project=$(echo "$query" | sed s/' \w*$'//)
+	project=$(echo "${query}" | sed s/' \w*$'//)
 	episode="${query##* }"
-	check_episode "$episode"
+	check_episode "${episode}"
 fi
 
 # Change directory to the project folder
 change_directory
 
 # Get episode to mux
-if [[ "$alt_folder" == "yes" ]]; then
+if [[ "${alt_folder}" == "yes" ]]; then
 
 	# Get arcs or seasons
-	[[ -z "$arc" ]] && arc=$(find . -maxdepth 1 -type d -name '[0-9]*' | cut -c 3- | sort | fzf --layout=reverse --prompt="Select an arc: ")
-	[[ -z "$arc" ]] && die "Arc was not selected by the user"
+	[[ -z "${arc}" ]] && arc=$(find . -maxdepth 1 -type d -name '[0-9]*' | cut -c 3- | sort | fzf --layout=reverse --prompt="Select an arc: ")
+	[[ -z "${arc}" ]] && die "Arc was not selected by the user"
 
 	# Get key of the arc or season.
 	# Generally, its the folder name of the arc, minus the space and all character uncapitalized.
-	key=$(echo "$arc" | cut -c 4- | tr -d "[:space:]" | tr "[:upper:]" "[:lower:]")
+	key=$(echo "${arc}" | cut -c 4- | tr -d "[:space:]" | tr "[:upper:]" "[:lower:]")
 
 	# In case the key does not follow the lower, unspaced rule, define exceptions in the config
-	exception=$(get_section "Exceptions" | grep "$key" | cut -d= -f2 | sed "s/^ //")
-	if [[ -n "$exception" ]]; then
-		key="$exception"
+	exception=$(get_section "Exceptions" | grep "${key}" | cut -d= -f2 | sed "s/^ //")
+	if [[ -n "${exception}" ]]; then
+		key="${exception}"
 	fi
-	[[ -z "$key" ]] && die "Key for an arc could not be determined."
+	[[ -z "${key}" ]] && die "Key for an arc could not be determined."
 
-	[[ -z "$episode" ]] && episode=$(find "$arc"/. -maxdepth 1 -type d -name '[0-9]*' | cut -d/ -f3 | sort | fzf --layout=reverse --multi --bind ctrl-a:toggle-all --prompt="Press ENTER for single, TAB for multiple and CTRL+a for all episodes.: ")
+	[[ -z "${episode}" ]] && episode=$(find "${arc}"/. -maxdepth 1 -type d -name '[0-9]*' | cut -d/ -f3 | sort | fzf --layout=reverse --multi --bind ctrl-a:toggle-all --prompt="Press ENTER for single, TAB for multiple and CTRL+a for all episodes.: ")
 
 else
 
-	[[ -z "$episode" ]] && episode=$(find . -maxdepth 1 -type d -name '[0-9]*' | cut -c 3- | sort | fzf --layout=reverse --multi --bind ctrl-a:toggle-all --prompt="Press ENTER for single, TAB for multiple and CTRL+a for all episodes.: ")
+	[[ -z "${episode}" ]] && episode=$(find . -maxdepth 1 -type d -name '[0-9]*' | cut -c 3- | sort | fzf --layout=reverse --multi --bind ctrl-a:toggle-all --prompt="Press ENTER for single, TAB for multiple and CTRL+a for all episodes.: ")
 
 fi
-[[ -z "$episode" ]] && die "Episode was not provided by the user."
+[[ -z "${episode}" ]] && die "Episode was not provided by the user."
 
 # Create an array with all the selected episodes
-mapfile -t ep <<<"$episode"
+mapfile -t ep <<<"${episode}"
 
 # Add history to config file
-if [[ "$alt_folder" == "yes" ]]; then
-	ep_hist=$(echo "$episode" | sed "s/^/${key}_/g" | tr "\n" "," | sed "s/,$//g")
+if [[ "${alt_folder}" == "yes" ]]; then
+	ep_hist=$(echo "${episode}" | sed "s/^/${key}_/g" | tr "\n" "," | sed "s/,$//g")
 else
-	ep_hist=$(echo "$episode" | tr "\n" "," | sed "s/,$//g")
+	ep_hist=$(echo "${episode}" | tr "\n" "," | sed "s/,$//g")
 fi
-hist=$(printf "%s = %s;%s" "$project" "$project_path" "$ep_hist")
-if ! grep -q "\[History\]" "$config"; then
-	printf "\n[History]\n\n" >>"$config"
+hist=$(printf "%s = %s;%s" "${project}" "${project_path}" "${ep_hist}")
+if ! grep -q "\[History\]" "${config}"; then
+	printf "\n[History]\n\n" >>"${config}"
 fi
-sed -i "/\[History\]/!b;n;c$hist" "$config"
+sed -i "/\[History\]/!b;n;c${hist}" "${config}"
 
 tput clear
 for i in "${ep[@]}"; do
 
-	if [[ "$alt_folder" == "yes" ]]; then
-		mux_key="$key"_"$i"
+	if [[ "${alt_folder}" == "yes" ]]; then
+		mux_key="${key}"_"${i}"
 	else
-		mux_key="$i"
+		mux_key="${i}"
 	fi
-	printf "Muxing \033[1;32m\"%s\" \033[0m- Episode \033[1;32m%s \033[0m\n" "$project" "$mux_key"
+	printf "Muxing \033[1;32m\"%s\" \033[0m- Episode \033[1;32m%s \033[0m\n" "${project}" "${mux_key}"
 	# Mux the episode
 	start_loading_animation
-	if ./gradlew --console=plain mux."$mux_key" >"$output" 2>&1; then
+	if ./gradlew --console=plain mux."${mux_key}" >"${output}" 2>&1; then
 		stop_loading_animation
-		all "$output"
+		all "${output}"
 	else
 		stop_loading_animation
-		warning "$output"
-		failure "$output"
+		warning "${output}"
+		failure "${output}"
 	fi
 done
