Improve coloring of text

diff --git a/muxsh b/muxsh
--- a/muxsh
+++ b/muxsh
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2059
 
 #GNU GENERAL PUBLIC LICENSE
 #                      Version 3, 29 June 2007
@@ -27,10 +26,6 @@ VERSION="0.1.0"
 
 # Variables
 dependencies=( fzf java mkvmerge curl sed grep cut  )
-c_reset="\033[0m"
-c_red="\033[1;31m"
-c_green="\033[1;32m"
-
 folder="${XDG_CACHE_HOME:-$HOME/.cache}/subkt"
 output="$folder/subkt.txt"
 config_folder="${XDG_CONFIG_HOME:-$HOME/.config}/muxkt"
@@ -74,8 +69,16 @@ stop_loading_animation() {
 
 # Functions
 die () {
-	printf "${c_red}%s${c_reset}\n" "$*" >&2
+	red_text "$*"
 	exit 1
+}
+
+red_text () {
+	printf "\033[1;31m\n%s\033[0m\n" "$*" >&2
+}
+
+green_text () {
+	printf "\033[1;31m\n%s\033[0m\n" "$*" >&2
 }
 
 # Check for update
@@ -192,7 +195,7 @@ EOF
 while getopts ':p:hon:e:rac:v' OPT; do
 	case $OPT in
 		:)
-			printf "$c_red%s.$c_reset\n" "Please provide an argument to -$OPTARG" >&2
+			red_text "Please provide an argument to -$OPTARG"
 			help_text | grep -e "USAGE" -e "-$OPTARG"
 			exit 2
 			;;
@@ -218,7 +221,7 @@ while getopts ':p:hon:e:rac:v' OPT; do
 
 			project=$(get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g" | grep -x "$OPTARG")
 			if [ -z "$project" ]; then
-				printf "The project named $OPTARG could not be found in the config.\n"
+				printf "The project named %s could not be found in the config.\n" "$OPTARG"
 				printf "The available projects are:\n"
 				get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g"	
 				exit 2
@@ -258,15 +261,16 @@ done
 shift $((OPTIND - 1))
 
 attachedFonts () {
-	printf "$c_green\nFonts Attached:\n$c_reset"
+	green_text "Fonts Attached"
 	grep -i -o "^Attaching.*[ot]tf" "$1" | sed "s/Attaching //"
 }
 
 tasksLists () {
-	printf "$c_green\nTasks Performed:\n$c_reset"
+	green_text "Tasks Performed:"
 	grep "Task :[^S]" "$1" | sed "
+	  s/^.*Task ://g
 	  s/\..*default//g
-	  s/.*chapters/Create Chapters/
+	  s/.*chapters/Create Chapters/g
 	  s/.*merge/Merge dialouge subtitles with opening/g
 	  s/.*mux/Mux the files into an mkv/g
 	  s/.*dub/Create dubtitles/g
@@ -274,18 +278,18 @@ tasksLists () {
 }
 
 chapter () {
-	printf "$c_green\nChapters Generated:\n$c_reset"
+	green_text "Chapters Generated:"
 	grep "CHAPTER" "$1"
 }
 
 warning () {
-	printf "$c_red\nWARNINGS:\n$c_reset"
+	red_text "WARNINGS:"
 	grep "conflicting PlayRes" "$1"
 	grep -e 'warning:' -e 'Validating fonts' "$1" | sed "s/warning: //; s/\.\.\.$//"
 }
 
 tracks () {
-	printf "$c_green\nMuxed Tracks:\n$c_reset"
+	green_text "Muxed Tracks:"
 	grep "^Track" "$1"
 }
 
@@ -411,7 +415,7 @@ for i in "${ep[@]}"; do
 	else
 		mux_key="$i"
 	fi
-	printf "Muxing $c_green\"%s\" $c_reset- Episode $c_green%s$c_reset\n" "$project" "$mux_key"
+	printf "Muxing \033[1;32m\"%s\" \033[0m- Episode \033[1;32m%s \033[0m\n" "$project" "$mux_key"
 	# Mux the episode
 	start_loading_animation
 	if ./gradlew --console=plain mux."$mux_key" > "$output" 2>&1; then
