Small fix

diff --git a/muxsh b/muxsh
--- a/muxsh
+++ b/muxsh
@@ -63,9 +63,9 @@ stop_loading_animation() {
 }
 
 # Create required directories and config file if they're not present
-[ ! -d "$folder" ] && mkdir -p "$folder"
-[ ! -d "$config_folder" ] && mkdir -p "$config_folder"
-[ -f "$config" ] || : > "$config"
+[[ ! -d "$folder" ]] && mkdir -p "$folder"
+[[ ! -d "$config_folder" ]] && mkdir -p "$config_folder"
+[[ -f "$config" ]] || : > "$config"
 
 # Functions
 die () {
@@ -84,7 +84,7 @@ green_text () {
 # Check for update
 check_update () {
 	update="$(curl -s "https://raw.githubusercontent.com/PhosCity/muxsh/main/muxsh" | diff -u "$0" -)"
-	if [ -n "$update" ]; then
+	if [[ -n "$update" ]]; then
 		printf "There seems to be a new version available in github.\nPlease get it from https://github.com/PhosCity/muxsh \n"
 		sleep 3
 	fi
@@ -114,17 +114,17 @@ config_add () {
 	while :; do
 		printf "Name of Project: "
 		read -r prj
-		if [ -z "$prj" ]; then
+		if [[ -z "$prj" ]]; then
 			echo "Project is needed for continuing."
 		else
 			printf "Path of the project: "
 			read -r pth
-			if [ ! -d "$pth" ]; then
+			if [[ ! -d "$pth" ]]; then
 				echo "Not a valid path."
 				pth=""
 			fi
 		fi
-		if [ -n "$prj" ] && [ -n "$pth" ]; then
+		if [[ -n "$prj" ]] && [[ -n "$pth" ]]; then
 			sed -i "/\[Project\]/a $prj = $pth" "$config"
 		fi
 		printf "Do you want to continue adding projects[y/n]: "
@@ -154,14 +154,14 @@ config_remove () {
 # Then cd to that directory.
 # Also if config is not found, then prompt user to add one.
 change_directory () {
-	if [ -z "$project" ]; then
+	if [[ -z "$project" ]]; then
 		if ! grep -q "\[Project\]" "$config" ; then
 			config_add
 		fi
 		project=$(get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g" | fzf)
 	fi
-	[ -z "$project" ] && die "Project was not selected by the user."
-	[ -z "$project_path" ] && project_path=$(get_section "Project" | grep "$project" | cut -d= -f2 | sed "s/\"//g;s/^ //g")
+	[[ -z "$project" ]] && die "Project was not selected by the user."
+	[[ -z "$project_path" ]] && project_path=$(get_section "Project" | grep "$project" | cut -d= -f2 | sed "s/\"//g;s/^ //g")
 	cd "$project_path" || die "Path in config is not correct."
 }
 
@@ -208,7 +208,7 @@ while getopts ':p:hon:e:rac:v' OPT; do
 			exit 0
 			;;
 		p)
-			if [ ! -d "$OPTARG" ]; then
+			if [[ ! -d "$OPTARG" ]]; then
 				die "$OPTARG is not a valid path."
 			else
 				project_path="$OPTARG"
@@ -217,10 +217,10 @@ while getopts ':p:hon:e:rac:v' OPT; do
 			fi
 			;;
 		n)
-			[ -s "$config" ] || die "No content found in config. Please add your projects to the config which is located at $config_folder"
+			[[ -s "$config" ]] || die "No content found in config. Please add your projects to the config which is located at $config_folder"
 
 			project=$(get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g" | grep -x "$OPTARG")
-			if [ -z "$project" ]; then
+			if [[ -z "$project" ]]; then
 				printf "The project named %s could not be found in the config.\n" "$OPTARG"
 				printf "The available projects are:\n"
 				get_section "Project" | grep "=" | cut -d= -f1 | sed "s/ $//g"	
@@ -251,7 +251,7 @@ while getopts ':p:hon:e:rac:v' OPT; do
 			echo "muxsh, Version: $VERSION"
 			exit 0
 			;;
-		?)
+		*)
 			echo "Invalid option: -${OPTARG}."
 			help_text
 			exit 1
@@ -343,10 +343,10 @@ for i in "${dependencies[@]}"
 do
 	dep_ch "$i"
 done
-[ -n "$missing_dep" ] && die "${missing_dep}not found. Please install all missing dependencies."
+[[ -n "$missing_dep" ]] && die "${missing_dep}not found. Please install all missing dependencies."
 
 # Read History
-if [ "$project" = "Repeat Last" ]; then
+if [[ "$project" = "Repeat Last" ]]; then
 	_hist=$(get_section "History" | tr -d "\n")
 	project=$(cut -d= -f1 <<< "$_hist" | sed "s/[[:space:]]*$//")
 	project_path=$(cut -d= -f2 <<< "$_hist" | cut -d';' -f1 | sed "s/^ //")
@@ -354,7 +354,7 @@ if [ "$project" = "Repeat Last" ]; then
 fi
 
 # Read query (Should be given in `<path to script> <project> <episode>` format)
-if [ -n "$*" ]; then
+if [[ -n "$*" ]]; then
 	query="$*"
 	# shellcheck disable=SC2001
 	project=$(echo "$query" | sed s/' \w*$'//)
@@ -366,11 +366,11 @@ fi
 change_directory
 
 # Get episode to mux
-if [ "$alt_folder" == "yes" ]; then
+if [[ "$alt_folder" == "yes" ]]; then
 
 	# Get arcs or seasons
-	[ -z "$arc" ] && arc=$(find . -maxdepth 1 -type d -name '[0-9]*' | cut -c 3- | sort | fzf --layout=reverse --prompt="Select an arc: ")
-	[ -z "$arc" ] && die "Arc was not selected by the user"
+	[[ -z "$arc" ]] && arc=$(find . -maxdepth 1 -type d -name '[0-9]*' | cut -c 3- | sort | fzf --layout=reverse --prompt="Select an arc: ")
+	[[ -z "$arc" ]] && die "Arc was not selected by the user"
 
 	# Get key of the arc or season.
 	# Generally, its the folder name of the arc, minus the space and all character uncapitalized.
@@ -378,25 +378,25 @@ if [ "$alt_folder" == "yes" ]; then
 
 	# In case the key does not follow the lower, unspaced rule, define exceptions in the config
 	exception=$(get_section "Exceptions" | grep "$key" | cut -d= -f2 | sed "s/^ //")
-	if [ -n "$exception" ]; then
+	if [[ -n "$exception" ]]; then
 		key="$exception"
 	fi
-	[ -z "$key" ] && die "Key for an arc could not be determined."
+	[[ -z "$key" ]] && die "Key for an arc could not be determined."
 
-	[ -z "$episode" ] && episode=$(find "$arc"/. -maxdepth 1 -type d -name '[0-9]*' | cut -d/ -f3 | sort | fzf --layout=reverse --multi --bind ctrl-a:toggle-all --prompt="Press ENTER for single, TAB for multiple and CTRL+a for all episodes.: ")
+	[[ -z "$episode" ]] && episode=$(find "$arc"/. -maxdepth 1 -type d -name '[0-9]*' | cut -d/ -f3 | sort | fzf --layout=reverse --multi --bind ctrl-a:toggle-all --prompt="Press ENTER for single, TAB for multiple and CTRL+a for all episodes.: ")
 
 else
 
-	[ -z "$episode" ] && episode=$(find . -maxdepth 1 -type d -name '[0-9]*' | cut -c 3- | sort | fzf --layout=reverse --multi --bind ctrl-a:toggle-all --prompt="Press ENTER for single, TAB for multiple and CTRL+a for all episodes.: ")
+	[[ -z "$episode" ]] && episode=$(find . -maxdepth 1 -type d -name '[0-9]*' | cut -c 3- | sort | fzf --layout=reverse --multi --bind ctrl-a:toggle-all --prompt="Press ENTER for single, TAB for multiple and CTRL+a for all episodes.: ")
 
 fi
-[ -z "$episode" ] && die "Episode was not provided by the user."
+[[ -z "$episode" ]] && die "Episode was not provided by the user."
 
 # Create an array with all the selected episodes
 mapfile -t ep <<< "$episode"
 
 # Add history to config file
-if [ "$alt_folder" == "yes" ]; then
+if [[ "$alt_folder" == "yes" ]]; then
 	ep_hist=$(echo "$episode" | sed "s/^/${key}_/g" | tr "\n" "," | sed "s/,$//g")
 else
 	ep_hist=$(echo "$episode" | tr "\n" "," | sed "s/,$//g")
@@ -410,7 +410,7 @@ sed -i "/\[History\]/!b;n;c$hist" "$config"
 tput clear
 for i in "${ep[@]}"; do
 
-	if [ "$alt_folder" == "yes" ]; then
+	if [[ "$alt_folder" == "yes" ]]; then
 		mux_key="$key"_"$i"
 	else
 		mux_key="$i"
